// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4aVWjd3bOPuz9iJiEirMiG1dCr_beeJo',
    appId: '1:1075902730433:web:06f70e1d1dc1184f474440',
    messagingSenderId: '1075902730433',
    projectId: 'vibescape-01',
    authDomain: 'vibescape-01.firebaseapp.com',
    databaseURL: 'https://vibescape-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibescape-01.firebasestorage.app',
    measurementId: 'G-QNHSZS9BP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALPAEJHwEjX4QKSAnjTT5egl5pnIShX1k',
    appId: '1:1075902730433:android:11351490d51def7f474440',
    messagingSenderId: '1075902730433',
    projectId: 'vibescape-01',
    databaseURL: 'https://vibescape-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibescape-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vLqpIqlFQD4EGsbE4vgwRGYAc9ObbWM',
    appId: '1:1075902730433:ios:4450f44f4e4b0e67474440',
    messagingSenderId: '1075902730433',
    projectId: 'vibescape-01',
    databaseURL: 'https://vibescape-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibescape-01.firebasestorage.app',
    iosBundleId: 'com.example.offlineMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vLqpIqlFQD4EGsbE4vgwRGYAc9ObbWM',
    appId: '1:1075902730433:ios:4450f44f4e4b0e67474440',
    messagingSenderId: '1075902730433',
    projectId: 'vibescape-01',
    databaseURL: 'https://vibescape-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibescape-01.firebasestorage.app',
    iosBundleId: 'com.example.offlineMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4aVWjd3bOPuz9iJiEirMiG1dCr_beeJo',
    appId: '1:1075902730433:web:da91609114da4bf8474440',
    messagingSenderId: '1075902730433',
    projectId: 'vibescape-01',
    authDomain: 'vibescape-01.firebaseapp.com',
    databaseURL: 'https://vibescape-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibescape-01.firebasestorage.app',
    measurementId: 'G-0T2LKZLBFD',
  );
}
