// Mocks generated by Mockito 5.4.4 from annotations
// in vibescape/test/unit/audio_player_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:audio_service/audio_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:on_audio_query/on_audio_query.dart' as _i4;
import 'package:on_audio_query_platform_interface/on_audio_query_platform_interface.dart'
    as _i2;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceModel_0 extends _i1.SmartFake implements _i2.DeviceModel {
  _FakeDeviceModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_1<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnAudioQuery].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnAudioQuery extends _i1.Mock implements _i4.OnAudioQuery {
  MockOnAudioQuery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> checkAndRequest({bool? retryRequest = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndRequest,
          [],
          {#retryRequest: retryRequest},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setLogConfig(_i2.LogConfig? logConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLogConfig,
          [logConfig],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.SongModel>> querySongs({
    _i2.SongSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
    bool? ignoreCase,
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #querySongs,
          [],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
            #ignoreCase: ignoreCase,
            #path: path,
          },
        ),
        returnValue: _i5.Future<List<_i2.SongModel>>.value(<_i2.SongModel>[]),
      ) as _i5.Future<List<_i2.SongModel>>);

  @override
  _i5.Future<List<_i2.AlbumModel>> queryAlbums({
    _i2.AlbumSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
    bool? ignoreCase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAlbums,
          [],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
            #ignoreCase: ignoreCase,
          },
        ),
        returnValue: _i5.Future<List<_i2.AlbumModel>>.value(<_i2.AlbumModel>[]),
      ) as _i5.Future<List<_i2.AlbumModel>>);

  @override
  _i5.Future<List<_i2.ArtistModel>> queryArtists({
    _i2.ArtistSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
    bool? ignoreCase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryArtists,
          [],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
            #ignoreCase: ignoreCase,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.ArtistModel>>.value(<_i2.ArtistModel>[]),
      ) as _i5.Future<List<_i2.ArtistModel>>);

  @override
  _i5.Future<List<_i2.PlaylistModel>> queryPlaylists({
    _i2.PlaylistSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
    bool? ignoreCase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryPlaylists,
          [],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
            #ignoreCase: ignoreCase,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.PlaylistModel>>.value(<_i2.PlaylistModel>[]),
      ) as _i5.Future<List<_i2.PlaylistModel>>);

  @override
  _i5.Future<List<_i2.GenreModel>> queryGenres({
    _i2.GenreSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
    bool? ignoreCase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryGenres,
          [],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
            #ignoreCase: ignoreCase,
          },
        ),
        returnValue: _i5.Future<List<_i2.GenreModel>>.value(<_i2.GenreModel>[]),
      ) as _i5.Future<List<_i2.GenreModel>>);

  @override
  _i5.Future<List<_i2.SongModel>> queryAudiosFrom(
    _i2.AudiosFromType? type,
    Object? where, {
    _i2.SongSortType? sortType,
    _i2.OrderType? orderType,
    bool? ignoreCase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAudiosFrom,
          [
            type,
            where,
          ],
          {
            #sortType: sortType,
            #orderType: orderType,
            #ignoreCase: ignoreCase,
          },
        ),
        returnValue: _i5.Future<List<_i2.SongModel>>.value(<_i2.SongModel>[]),
      ) as _i5.Future<List<_i2.SongModel>>);

  @override
  _i5.Future<List<dynamic>> queryWithFilters(
    String? argsVal,
    _i2.WithFiltersType? withType, {
    dynamic args,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryWithFilters,
          [
            argsVal,
            withType,
          ],
          {#args: args},
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<_i6.Uint8List?> queryArtwork(
    int? id,
    _i2.ArtworkType? type, {
    _i2.ArtworkFormat? format,
    int? size,
    int? quality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryArtwork,
          [
            id,
            type,
          ],
          {
            #format: format,
            #size: size,
            #quality: quality,
          },
        ),
        returnValue: _i5.Future<_i6.Uint8List?>.value(),
      ) as _i5.Future<_i6.Uint8List?>);

  @override
  _i5.Future<List<_i2.SongModel>> queryFromFolder(
    String? path, {
    _i2.SongSortType? sortType,
    _i2.OrderType? orderType,
    _i2.UriType? uriType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryFromFolder,
          [path],
          {
            #sortType: sortType,
            #orderType: orderType,
            #uriType: uriType,
          },
        ),
        returnValue: _i5.Future<List<_i2.SongModel>>.value(<_i2.SongModel>[]),
      ) as _i5.Future<List<_i2.SongModel>>);

  @override
  _i5.Future<List<String>> queryAllPath() => (super.noSuchMethod(
        Invocation.method(
          #queryAllPath,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> createPlaylist(
    String? name, {
    String? author,
    String? desc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlaylist,
          [name],
          {
            #author: author,
            #desc: desc,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removePlaylist(int? playlistId) => (super.noSuchMethod(
        Invocation.method(
          #removePlaylist,
          [playlistId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> addToPlaylist(
    int? playlistId,
    int? audioId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToPlaylist,
          [
            playlistId,
            audioId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeFromPlaylist(
    int? playlistId,
    int? audioId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromPlaylist,
          [
            playlistId,
            audioId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> moveItemTo(
    int? playlistId,
    int? from,
    int? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveItemTo,
          [
            playlistId,
            from,
            to,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> renamePlaylist(
    int? playlistId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renamePlaylist,
          [
            playlistId,
            newName,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> permissionsStatus() => (super.noSuchMethod(
        Invocation.method(
          #permissionsStatus,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> permissionsRequest({bool? retryRequest = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #permissionsRequest,
          [],
          {#retryRequest: retryRequest},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.DeviceModel> queryDeviceInfo() => (super.noSuchMethod(
        Invocation.method(
          #queryDeviceInfo,
          [],
        ),
        returnValue: _i5.Future<_i2.DeviceModel>.value(_FakeDeviceModel_0(
          this,
          Invocation.method(
            #queryDeviceInfo,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DeviceModel>);

  @override
  _i5.Future<bool> scanMedia(String? path) => (super.noSuchMethod(
        Invocation.method(
          #scanMedia,
          [path],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [AudioHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioHandler extends _i1.Mock implements _i7.AudioHandler {
  MockAudioHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ValueStream<_i7.PlaybackState> get playbackState => (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _FakeValueStream_1<_i7.PlaybackState>(
          this,
          Invocation.getter(#playbackState),
        ),
      ) as _i3.ValueStream<_i7.PlaybackState>);

  @override
  _i3.ValueStream<List<_i7.MediaItem>> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeValueStream_1<List<_i7.MediaItem>>(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i3.ValueStream<List<_i7.MediaItem>>);

  @override
  _i3.ValueStream<String> get queueTitle => (super.noSuchMethod(
        Invocation.getter(#queueTitle),
        returnValue: _FakeValueStream_1<String>(
          this,
          Invocation.getter(#queueTitle),
        ),
      ) as _i3.ValueStream<String>);

  @override
  _i3.ValueStream<_i7.MediaItem?> get mediaItem => (super.noSuchMethod(
        Invocation.getter(#mediaItem),
        returnValue: _FakeValueStream_1<_i7.MediaItem?>(
          this,
          Invocation.getter(#mediaItem),
        ),
      ) as _i3.ValueStream<_i7.MediaItem?>);

  @override
  _i3.ValueStream<_i7.RatingStyle> get ratingStyle => (super.noSuchMethod(
        Invocation.getter(#ratingStyle),
        returnValue: _FakeValueStream_1<_i7.RatingStyle>(
          this,
          Invocation.getter(#ratingStyle),
        ),
      ) as _i3.ValueStream<_i7.RatingStyle>);

  @override
  _i3.ValueStream<_i7.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
        Invocation.getter(#androidPlaybackInfo),
        returnValue: _FakeValueStream_1<_i7.AndroidPlaybackInfo>(
          this,
          Invocation.getter(#androidPlaybackInfo),
        ),
      ) as _i3.ValueStream<_i7.AndroidPlaybackInfo>);

  @override
  _i5.Stream<dynamic> get customEvent => (super.noSuchMethod(
        Invocation.getter(#customEvent),
        returnValue: _i5.Stream<dynamic>.empty(),
      ) as _i5.Stream<dynamic>);

  @override
  _i3.ValueStream<dynamic> get customState => (super.noSuchMethod(
        Invocation.getter(#customState),
        returnValue: _FakeValueStream_1<dynamic>(
          this,
          Invocation.getter(#customState),
        ),
      ) as _i3.ValueStream<dynamic>);

  @override
  _i5.Future<void> prepare() => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> prepareFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> playMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #playMediaItem,
          [mediaItem],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> click([_i7.MediaButton? button = _i7.MediaButton.media]) =>
      (super.noSuchMethod(
        Invocation.method(
          #click,
          [button],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItem,
          [mediaItem],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addQueueItems(List<_i7.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItems,
          [mediaItems],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> insertQueueItem(
    int? index,
    _i7.MediaItem? mediaItem,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueueItem,
          [
            index,
            mediaItem,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateQueue(List<_i7.MediaItem>? queue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueue,
          [queue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMediaItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaItem,
          [mediaItem],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeQueueItem(_i7.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItem,
          [mediaItem],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeQueueItemAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeQueueItemAt,
          [index],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToNext() => (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fastForward() => (super.noSuchMethod(
        Invocation.method(
          #fastForward,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> rewind() => (super.noSuchMethod(
        Invocation.method(
          #rewind,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToQueueItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #skipToQueueItem,
          [index],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRating(
    _i7.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            rating,
            extras,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCaptioningEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setCaptioningEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRepeatMode(_i7.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepeatMode,
          [repeatMode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setShuffleMode(_i7.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShuffleMode,
          [shuffleMode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekBackward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [begin],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekForward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [begin],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customAction,
          [
            name,
            extras,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<void> onTaskRemoved() => (super.noSuchMethod(
        Invocation.method(
          #onTaskRemoved,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> onNotificationDeleted() => (super.noSuchMethod(
        Invocation.method(
          #onNotificationDeleted,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildren,
          [
            parentMediaId,
            options,
          ],
        ),
        returnValue: _i5.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i5.Future<List<_i7.MediaItem>>);

  @override
  _i3.ValueStream<Map<String, dynamic>> subscribeToChildren(
          String? parentMediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToChildren,
          [parentMediaId],
        ),
        returnValue: _FakeValueStream_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #subscribeToChildren,
            [parentMediaId],
          ),
        ),
      ) as _i3.ValueStream<Map<String, dynamic>>);

  @override
  _i5.Future<_i7.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaItem,
          [mediaId],
        ),
        returnValue: _i5.Future<_i7.MediaItem?>.value(),
      ) as _i5.Future<_i7.MediaItem?>);

  @override
  _i5.Future<List<_i7.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i5.Future<List<_i7.MediaItem>>.value(<_i7.MediaItem>[]),
      ) as _i5.Future<List<_i7.MediaItem>>);

  @override
  _i5.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidSetRemoteVolume,
          [volumeIndex],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> androidAdjustRemoteVolume(
          _i7.AndroidVolumeDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidAdjustRemoteVolume,
          [direction],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
